# More help on link above
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    chmod +x zsh-install.sh && chmod +x tools-zsh-install.sh
  displayName: 'Conceder permissão de execução aos scripts'

- script: |
    ./zsh-install.sh
  displayName: 'Testar instalação do zsh-install.sh'

- script: |
    ./tools-zsh-install.sh
  displayName: 'Testar instalação do tools-zsh-install.sh'


