# More help on link above
# https://aka.ms/yaml

trigger:
- master
pr:
- master
- releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sh ./zsh-install.sh
  displayName: 'Instalando Shell ZSH...'

- task: Bash@3
  inputs:
    filePath: '$(Build.SourcesDirectory)/tools-zsh-install.sh'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
-   script: |
      sh ./tools-zsh-install.sh
    displayName: 'Instalando ZSH pluguins...'