# More help on link above
# https://aka.ms/yaml

trigger:
- master
pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: < 2 | sh ./zsh-install.sh
  displayName: 'zsh-install...'

- task: script-retryer@0
  inputs:
    targetInterperter: 'bash'
    targetType: 'inline'
    script: '< enter | sh ./tools-zsh-install.sh'
