# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
  filePath: '$(Build.SourcesDirectory)/zsh-install.sh'
  workingDirectory: '$(System.DefaultWorkingDirectory)'
- script: sh zsh-install.sh
  displayName: 'zsh-install.sh'


- task: Bash@3
  inputs:
    filePath: '$(Build.SourcesDirectory)/tools-zsh-install.sh'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
-   script: |
      sh tools-zsh-install.sh
    displayName: 'tools-zsh-install.sh'