# More help on link above
# https://aka.ms/yaml

trigger:
- master
pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: /bin/bash -c "$(curl -sL https://git.io/vokNn)"
  displayName: 'install apt-fast...'

- task: Bash@3
  inputs:
    filePath: '$(Build.SourcesDirectory)/zsh-install.sh'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
-   script: |
      < 2 | sh ./zsh-install.sh
    displayName: 'zsh-install...'
    
- task: Bash@3
  inputs:
    filePath: '$(Build.SourcesDirectory)/tools-zsh-install.sh'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
-   script: |
      < enter | sh ./tools-zsh-install.sh
    displayName: 'zsh-tools...'

