# More help on link above
# https://aka.ms/yaml

trigger:
- master
pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: < 2 | sh ./zsh-install.sh
  displayName: 'zsh-install...'
- script: < enter | sh ./tools-zsh-install.sh  
  displayName: 'zsh-tools...'   

