# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Iniciando script!
  displayName: 'Exibindo msg'


- task: Bash@3
  inputs:
    filePath: '$(Build.SourcesDirectory)/zsh-install.sh'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
-   script: |
      sh zsh-install.sh
      2
      done
    displayName: 'Executando script mutiplo'