name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Conceder permissão de execução aos scripts
        run: chmod +x zsh-install.sh && chmod +x tools-zsh-install.sh
        
      - name: Testar instalação do zsh-install.sh
        run: ./zsh-install.sh

      - name: Testar instalação do tools-zsh-install.sh
        run: ./tools-zsh-install.sh